"""Chat domain models.

These types are the contract between the service layer and *any* client.
The Streamlit app, the FastAPI adapter and the test suite all speak in
:class:`Message` and :class:`ChatResponse`; none of them knows how the other
renders. That is what makes the UI swappable rather than merely "modular" in
a diagram.

Everything here is a Pydantic model rather than a plain dataclass so that the
same definitions serve three jobs at once: runtime validation, JSON
serialisation for session persistence, and -- once the FastAPI adapter
exists -- an OpenAPI schema generated for free.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


def _utc_now() -> datetime:
    """Return an aware UTC timestamp."""
    return datetime.now(tz=timezone.utc)


def _new_id() -> str:
    """Return a short unique identifier."""
    return uuid.uuid4().hex[:12]


class Role(str, Enum):
    """Author of a message.

    Inherits from :class:`str` so instances serialise to plain JSON strings
    and compare cleanly against provider SDK literals.
    """

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class ResponseSource(str, Enum):
    """How a given assistant reply was produced.

    Recorded on every response because it drives both the UI badge and the
    evaluation harness: a refusal produced by the deterministic guardrail is
    a categorically different event from one produced by the model, and the
    two must be measurable separately.
    """

    #: Generated by the model, grounded in retrieved knowledge-base context.
    GROUNDED = "grounded"
    #: Generated by the model from parametric knowledge, no retrieval hits.
    MODEL_ONLY = "model_only"
    #: Deterministic guardrail response; no model call was made.
    GUARDRAIL = "guardrail"
    #: Emergency or crisis template; no model call was made.
    ESCALATION = "escalation"
    #: Error path; a safe fallback message was substituted.
    FALLBACK = "fallback"


class Citation(BaseModel):
    """A reference to the knowledge-base passage supporting a claim.

    Citations are only ever constructed from chunks that actually cleared the
    retrieval score threshold. The assistant never fabricates a source, which
    is the single most important anti-hallucination property of the RAG layer.
    """

    model_config = ConfigDict(frozen=True)

    marker: int = Field(description="1-based index rendered inline as [1], [2].")
    title: str = Field(description="Human-readable document title.")
    source: str = Field(description="Originating publisher, e.g. 'MedlinePlus'.")
    url: str | None = Field(default=None, description="Public URL, when available.")
    snippet: str = Field(
        default="", description="Short excerpt shown when a citation is expanded."
    )
    score: float = Field(
        default=0.0, ge=0.0, le=1.0, description="Similarity score of the match."
    )


class Message(BaseModel):
    """A single message in a conversation."""

    id: str = Field(default_factory=_new_id)
    role: Role
    content: str
    created_at: datetime = Field(default_factory=_utc_now)
    citations: list[Citation] = Field(default_factory=list)
    source: ResponseSource | None = Field(
        default=None, description="Set on assistant messages only."
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Non-rendered diagnostics: latency, token counts, model id.",
    )

    def to_provider_dict(self) -> dict[str, str]:
        """Return the minimal ``{role, content}`` shape provider SDKs expect.

        Deliberately drops citations, ids and metadata: sending them would
        waste tokens and invite the model to imitate the schema in its prose.
        """
        return {"role": self.role.value, "content": self.content}


class ChatResponse(BaseModel):
    """The complete outcome of one chat turn.

    Returned by the service layer to whichever client asked for it. Carries
    enough information for a UI to render badges, citations and disclaimers
    without re-deriving any of it.
    """

    message: Message
    source: ResponseSource
    citations: list[Citation] = Field(default_factory=list)
    disclaimer: str | None = Field(
        default=None, description="Appended by the safety layer when required."
    )
    refused: bool = Field(
        default=False, description="True when the guardrail declined to answer."
    )
    latency_ms: int = Field(default=0, ge=0)
    turn_id: str = Field(default_factory=_new_id)

    @property
    def is_grounded(self) -> bool:
        """True when the answer was supported by retrieved documents."""
        return self.source is ResponseSource.GROUNDED and bool(self.citations)


class Conversation(BaseModel):
    """An ordered sequence of messages plus its persistence identity."""

    session_id: str = Field(default_factory=_new_id)
    title: str = Field(default="New chat")
    messages: list[Message] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=_utc_now)
    updated_at: datetime = Field(default_factory=_utc_now)
    summary: str | None = Field(
        default=None,
        description="Rolling summary of turns older than the verbatim window.",
    )

    def add(self, message: Message) -> "Conversation":
        """Append a message and refresh the update timestamp.

        Returns ``self`` so calls can be chained.
        """
        self.messages.append(message)
        self.updated_at = _utc_now()
        return self

    def recent(self, max_turns: int) -> list[Message]:
        """Return the trailing window of messages replayed into the prompt.

        Args:
            max_turns: Number of user/assistant *pairs* to retain.
        """
        return self.messages[-(max_turns * 2) :] if max_turns > 0 else []

    def derive_title(self, max_length: int = 48) -> str:
        """Return a sidebar title taken from the first user message.

        Falls back to the default title while the conversation is empty.
        """
        for message in self.messages:
            if message.role is Role.USER:
                text = " ".join(message.content.split())
                if len(text) <= max_length:
                    return text
                return text[: max_length - 1].rstrip() + "\u2026"
        return self.title
